#------------SpringBoot 启动配置-----------------#
---
#默认配置
server:
  port: 8080
#切换配置
spring:
  profiles:
    active: dev
---
#开发环境
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: dev
---
#测试环境
server:
  port: 8082
spring:
  config:
    activate:
      on-profile: test
---
#生产环境
server:
  port: 8083
spring:
  config:
    activate:
      on-profile: prod

#-----------------------------------------------#
#-----------------Thymeleaf 配置-----------------#
---
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

#-----------------------------------------------#
#-----------------国际化资源 配置-----------------#
#---
#spring:
#  messages:
#    basename: i18n.language

#-----------------------------------------------#
#-----------------数据源连接信息-------------------#
---
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/histudent?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

#-----------------------------------------------#
#-------------Druid 数据源连接池配置---------------#
---
spring:
  datasource:
    druid:
      #初始化连接大小
      initial-size: 5
      #最小连接池数量
      min-idle: 5
      #最大连接池数量
      max-active: 20
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #测试连接
      validation-query: SELECT 1 FROM DUAL
      #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-while-idle: true
      #获取连接时执行检测，建议关闭，影响性能
      test-on-borrow: false
      #归还连接时执行检测，建议关闭，影响性能
      test-on-return: false
      #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      pool-prepared-statements: false
      #开启poolPreparedStatements后生效
      max-pool-prepared-statement-per-connection-size: 20
      #配置扩展插件，常用的插件有=>stat:监控统计  wall:防御sql注入
      filters: stat,wall
      #通过connectProperties属性来打开mergeSql功能;慢SQL记录
      connection-properties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'
#-----------------------------------------------#
#---------------Druid 监控配置信息----------------#
---
spring:
  datasource:
    druid:
      #StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        #是否开启内置监控页面，默认值为 false
        enabled: true
        #StatViewServlet 的映射路径，即内置监控页面的访问地址
        url-pattern: '/druid/*'
        #是否启用重置按钮
        reset-enable: true
        #内置监控页面的登录页用户名 username
        login-username: admin
        #内置监控页面的登录页密码 password
        login-password: admin
      #WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        #是否开启内置监控中的 Web-jdbc 关联监控的数据
        enabled: true
        #匹配路径
        url-pattern: '/*'
        #排除路径
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        #是否监控session
        session-stat-enable: true
      #Spring监控AOP切入点，如x.y.z.abc.*,配置多个英文逗号分隔
      aop-patterns: xyz.mushan.www.*
#-----------------------------------------------#
#---------------Druid 监控配置信息----------------#
---
spring:
  datasource:
    druid:
      # 对配置已开启的 filters 即 stat(sql 监控)  wall（防火墙）
      filter:
        #配置StatFilter (SQL监控配置)
        stat:
          #开启 SQL 监控
          enabled: true
          #慢查询
          slow-sql-millis: 1000
          #记录慢查询 SQL
          log-slow-sql: true

        #配置WallFilter (防火墙配置)
        wall:
          #开启防火墙
          enabled: true
          config:
            #允许更新操作
            update-allow: true
            #禁止删表操作
            drop-table-allow: false
            #允许插入操作
            insert-allow:  true
            #删除数据操作
            delete-allow: true
#-----------------------------------------------#
#------------------MyBatis配置-------------------#
---
#mybatis:
#  # 指定 mapper.xml 的位置
#  mapper-locations: classpath:mapper/*.xml
#  #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
#  type-aliases-package: xyz.mushan.www.mapper
#  configuration:
#    #默认开启驼峰命名法，可以不用设置该属性
#    map-underscore-to-camel-case: true
#-----------------------------------------------#

#-----------------------------------------------#
#------------------MyBatis-plus配置-------------------#
---
# 日志配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
#-----------------------------------------------#